on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION : "ap-south-1" 

jobs:
  AssumeRoleAndCallIdentity:
    runs-on: self-hosted
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          echo "hello"
          ls
